musicrec/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'musicrec.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rec/', include('rec.urls',namespace='rec')),
)

rec/urls.py
from django.conf.urls import patterns, url
from rec import views

urlpatterns = patterns('',
    url(r'^$',views.index,name="index" ),
    url(r'^each/$',views.each,name="each" ),
    url(r'^vote/$',views.vote,name="vote" ),
    url(r'^uauth/$',views.uauth,name="uauth" ),
)

rec/models.py
from django.db import models

# Create your models here.

musicrec/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')
    

rec/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

import sqlite3
import json

database = "big.db"

# Create your views here.

def index(request):
    uid = request.GET.get('uid','user3')

    conn = sqlite3.connect(database)
    cursor = conn.cursor()

    '''
    cursor.execute("DROP TABLE if exists users")
    cursor.execute("DROP TABLE if exists songs")
    cursor.execute("DROP TABLE if exists data")

    cursor.execute("CREATE table if not exists users(user_id text,name text,password text)")
    cursor.execute("CREATE table if not exists songs(song_id text,name text,artist text,url text, votes text)")
    cursor.execute("CREATE table if not exists data(user_id text, song_id text, vote text)")

    users = [('batman','Bruce','nananana'),
             ('mia','MK','mama'),
             ('jarjar','JB','binks'),
             ('joker','Joe','hahahaha')]

    songs = [('x1','lala','fakira','http://song1','0'),
             ('x2','jaja','print','http://song2','0'),
             ('x3','tata','dollar','http://song3','0'),
             ('x4','wawa','ra67','http://song4','0')]

    data = [('batman','x1','1'),
            ('batman','x2','1'),
            ('mia','x2','1'),
            ('jarjar','x2','1'),
            ('jarjar','xj','1'),
            ('jarjar','x1','1'),
            ('mia','xx','1'),
            ('joker','x1','1'),
            ('joker','x3','1'),
            ('joker','x2','1')]

    for x in users:
        cursor.execute("INSERT INTO users values(?,?,?)",x)

    for x in songs:
        cursor.execute("INSERT INTO songs values(?,?,?,?,?)",x)

    for x in data:
        cursor.execute("INSERT INTO data values(?,?,?)",x)
    conn.commit()
    '''

    users = cursor.execute("select user_id from users where user_id != ?",(uid,))
    users = cursor.fetchall()

    min_score = 0

    similar_users = []

    for u in users:
        u = u[0]
        score = get_score(uid,u)
        if len(similar_users) < 20 or score >= min_score:
            min_score = min(min_score,score)
            similar_users.append((u,score))
            insertionSort(similar_users)

    rec = []

    usongs = cursor.execute("select song_id from data where user_id = ?",(uid,))
    usongs = cursor.fetchall()
    for i in range(len(usongs)):
        usongs[i] = usongs[i][0]
    #print(usongs)

    for us in similar_users:
        if len(rec)>= 20 :
            break
        songs = cursor.execute("select song_id from data where user_id = ?",(us[0],))
        songs = songs.fetchall()
        for s in songs:
            if s[0] not in usongs and s[0] not in rec:
                rec.append(Song.get_song(s[0]))


    conn.close()
    #output = json.dumps(rec)
    #return HttpResponse(output)
    #return JsonResponse({'recommeded':rec})
    return render(request,'rec/home.html', {'recomm' : rec,'uid':uid})

class Song():
    def __init__(self,song_id,name,artist,url,votes=0):
        self.song_id = song_id
        self.name = name
        self.artist = artist
        self.url = url
        self.url = votes

    @staticmethod
    def get_song(sid):
        conn = sqlite3.connect(database)
        cursor = conn.cursor()
        x = cursor.execute("SELECT * FROM songs where song_id = ?",(sid,))
        row = x.fetchone()
        s = Song(row[0],row[1],row[2],row[3],row[4])
        conn.close()
        return s

def each(request):
    song_id = request.GET.get('sid','')
    uid = request.GET.get('uid','')
    song = Song.get_song(song_id)
    return render(request,'rec/other.html', {'song' : song,'uid':uid})

def vote(request):
    song_id = request.GET.get('sid','')
    uid = request.GET.get('uid','')
    vote = request.GET.get('vote','1')
    insert_data(uid,song_id,vote)

    '''
    insert_data('user43','song53','-1')
    conn = sqlite3.connect(database)
    cursor = conn.cursor()
    (uid,song_id,vote) = cursor.execute("SELECT * FROM data WHERE user_id = ? and song_id = ?",('user43','song53')).fetchone()
    conn.close()
    output = uid+song_id+vote
    return HttpResponse(output)
    '''
    
    url = "%s?uid=%s"%(reverse('rec:index'),uid)
    return HttpResponseRedirect(url)


def insert_data(uid,sid,vote):
    conn = sqlite3.connect(database)
    cursor = conn.cursor()
    x = cursor.execute("SELECT * FROM data WHERE user_id = ? and song_id = ?",(uid,sid))
    y = x.fetchone()
    xs = cursor.execute("SELECT votes from songs where song_id = ?",(sid,))
    cur_votes = int(xs.fetchone()[0])
    if y != None:
        cursor.execute("UPDATE data SET vote = ? WHERE user_id = ? and song_id = ?",(str(vote),uid,sid))
        eff_votes = cur_votes - int(y[2]) + int(vote)
        cursor.execute("UPDATE songs SET votes = ? WHERE song_id = ?",(str(eff_votes),sid))
    else :
        cursor.execute("INSERT INTO data VALUES(?,?,?)",(uid,sid,vote))
        eff_votes = cur_votes + int(vote)
        cursor.execute("UPDATE songs SET votes = ? WHERE song_id = ?",(str(eff_votes),sid))
    conn.commit()
    conn.close()

def get_score(u1,u2): #consider negative return as well
    score = 0
    conn = sqlite3.connect(database)
    cursor = conn.cursor()
    d1 = cursor.execute("SELECT * FROM data WHERE user_id = ?",(u1,))
    d1 = d1.fetchall()
    d2 = cursor.execute("SELECT * FROM data WHERE user_id = ?",(u2,))
    d2 = d2.fetchall()
    for x in d1:
        for y in d2:
            if x[1] == y[1] and x[2] == y[2]:
                score += 1
    conn.close()
    return score



def insertionSort(alist):
    for index in range(1,len(alist)):
        currentvalue = alist[index]
        position = index
        while position>0 and int(alist[position-1][1])<int(currentvalue[1]):
            alist[position]=alist[position-1]
            position = position-1
        alist[position]=currentvalue


def uauth(request):
    uid = request.POST.get('uid','')
    password = request.POST.get('password','')
    
    conn = sqlite3.connect(database)
    cursor = conn.cursor()
    users = cursor.execute("select user_id from users where user_id = ? and password = ?",(uid,password))
    y = users.fetchone()
    conn.close()
    #return HttpResponse(print(y))
    
    if y==None:
        return render(request,'home.html')
    url = "%s?uid=%s"%(reverse('rec:index'),uid)
    return HttpResponseRedirect(url)
    

rec/templates/rec/home.html
{% load staticfiles %}  

<html>
<link rel="stylesheet" type="text/css" href="{% static 'rec/home.css' %}" />
 <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<body onload="window.resizeTo(50,50)" style="background:url({%static 'rec/bd.jpg'%}); no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;
  opacity:0.8;">
  <h1 style="color:white;text-align:center;">Recommended List</h1><div>
   
  

<div style="margin-left:45%;">
   <a href="\rec?uid={{uid}}" class="btn btn-info btn-lg" style="background:black;">
          <span class="glyphicon glyphicon-refresh"></span> Refresh
        </a></div>
		<p>
		</p>
 <div style="margin-left:31%;">

  <ul>
    <br/>
  {% for r in recomm %}
    <li>
      <!--<img src="download.png" width="42" height="42"  />-->
      <h3 class="SN">{{r.name}}</h3><h4>{{r.artist}}</h4><a href="/rec/each?sid={{r.song_id}}&uid={{uid}}" class="b2">Listen</a>
      <p><br/></p>
  <hr></hr>
  {% endfor %}
  <ul>s
      
</div>

</body>
</html>

rec/templates/rec/other.html
{% load staticfiles %}  

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  
 
 <link href="{% static 'rec/home.css' %}" rel="stylesheet">
  </head>
<body onload="window.resizeTo(50,50)" style="background:url({% static 'rec/calendar.png' %}); no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;">
  <!--<div class ="center-block" style="width:250px;margin-top:250px;margin-left:800px;">  -->
  <div class="center">
  <a href="\rec\?uid={{uid}}" class="btn btn-info btn-lg" style="color:white;float:right;background-color:transparent;border-color:transparent;">
          <span class="glyphicon glyphicon-back"></span> Back
        </a>
  
  
  <div text-align="center">
  <h2 style="color:white;">{{song.name}}</h2>
  <h3 style="color:white;"><span style="color:#c1c0c0;">by </span> {{song.artist}}</h3>

  <audio style="margin-left:40%;" src="https://freemusicarchive.org/music/no_curator/G8/Run_With_It/G8_-_11_-_Sidewalk_To_Somewhere.mp3" controls="controls">
    Your browser does not support the audio element.
  </audio>

  <div style="margin-left:45%;">  
   <a href="{{song.url}}" class="btn btn-info btn-lg" style="background:black;">
          <span class="glyphicon glyphicon-download-alt"></span> Download Song
    </a>
  </div>

  <!--
  <iframe class="centered-thing" width="480" height="390" position:"center" src="https://www.youtube.com/embed/hqiNL4Hn04A" frameborder="0" allowfullscreen></iframe> 
  -->
  </div>
  <a href="/rec/vote?sid={{song.song_id}}&uid={{uid}}&vote=1" class="btn btn-info btn-lg" style="background-color:black;">
          <span class="glyphicon glyphicon-thumbs-up"></span> Like
        </a>
    
      <a href="/rec/vote?sid={{song.song_id}}&uid={{uid}}&vote=-1" class="btn btn-info btn-lg" style="float:right;background-color:black;">
          <span class="glyphicon glyphicon-thumbs-down"></span> Dislike
        </a>
    
  <div>
</body>
</html>

templates/home.html
{% load staticfiles %}  
<body onload="window.resizeTo(50,50)" style="background:url({% static 'rec/calendar.png' %}); no-repeat center center fixed; 
  -webkit-background-size: cover;
  -moz-background-size: cover;
  -o-background-size: cover;
  background-size: cover;">
<h1>Login</h1>

<form action="{% url 'rec:uauth' %}" method="post">
{% csrf_token %}
Username : 
<input type="text" name="uid"><br/><br/>
Password :&nbsp;
<input type="password" name="password"><br/><br/>
<input type="submit">
</form>
</body>